version: 0.2
phases:
  install:
    commands:
    - curl -sL https://deb.nodesource.com/setup_12.x | -E bash -
    - apt install -y nodejs
    - apt install -y npm
  pre_build:
    commands:
    - npm i
  build:
    commands:
    - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build