version: 0.2
phases:
  install:
    commands:
    - apt install curl
    - apt install nodejs
    - apt install npm
  pre_build:
    commands:
    - npm i
  build:
    commands:
    - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build